### ISSUE TITLE
Controller input

### ISSUE THREAD

**Issue by DanielOaks** [3dAnon/PoniGame#3]
I'm playing with this using [InControl](https://github.com/pbhogan/InControl). Controller input in Unity looks really, really messy, which is why some other library should handle it if possible!

**Comment by ghost** [comment]
In the past I've written my own controls system build on top of Unity's, rather then any sort of direct controller access. That is quite quick to do and usually works well enough. A quick alternative is worth looking in to though.

**Comment by DanielOaks** [comment]
That'd probably be good! I'm mostly looking into this because I'm unfamiliar with Unity's controller system (and it looking not very nice in terms of no automatic mappings, just guess what buttons are what).

**edit:** I've gotten the controller stuff working. I'll make it work with all the buttons and clean it up before I send a PR.
