### ISSUE TITLE
'Sprint/run mode' / animation

### ISSUE THREAD

**Issue by DanielOaks** [3dAnon/PoniGame#5]
Basically, for gamepads, having to hold down a button to run can get really tiring and annoying. Most games let you press a button and enter a 'sprint/run mode'.

When you press the button, the player should enter a lower, more 'alert' idle pose, and whenever they move they automatically run instead of just walking.

I'm having a very rough play with this myself, but considering it involves animation and I've never done animation before, I'm picking up the tools as I go. It's all new and weird. If someone could possibly do up the more alert idle animation, it'd be appreciated. Should make controls nicer on gamepads (and maybe also for a button in the menu to use toggle-to-sprint instead of push-to-sprint).

**Comment by ghost** [comment]
Alright, should be simple enough to have both a toggle button and another push to enter the opposite state temporarily. I like the alert state idea. I'll try to whip up an animation soon.

**Comment by DanielOaks** [comment]
Awesome, thanks.

**Comment by ghost** [comment]
When "C" is pressed or one the gamepad action buttons, the run state is toggled
